package org.fiware.iam.ccs.model;

@jakarta.annotation.Generated("org.openapitools.codegen.languages.MicronautCodegen")
@io.micronaut.core.annotation.Introspected
public class ProblemDetailsVO {

	public static final String JSON_PROPERTY_TYPE = "type";
	public static final String JSON_PROPERTY_TITLE = "title";
	public static final String JSON_PROPERTY_STATUS = "status";
	public static final String JSON_PROPERTY_DETAIL = "detail";
	public static final String JSON_PROPERTY_INSTANCE = "instance";

	/** An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type. */
	@com.fasterxml.jackson.annotation.JsonProperty(JSON_PROPERTY_TYPE)
	@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
	private java.net.URI type;

	/** A short summary of the problem type. */
	@com.fasterxml.jackson.annotation.JsonProperty(JSON_PROPERTY_TITLE)
	@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
	private String title;

	/** The HTTP status code generated by the origin server for this occurrence of the problem. */
	@com.fasterxml.jackson.annotation.JsonProperty(JSON_PROPERTY_STATUS)
	@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
	private Integer status;

	/** A human readable explanation specific to this occurrence of the problem. */
	@com.fasterxml.jackson.annotation.JsonProperty(JSON_PROPERTY_DETAIL)
	@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
	private String detail;

	/** An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
	@com.fasterxml.jackson.annotation.JsonProperty(JSON_PROPERTY_INSTANCE)
	@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
	private java.net.URI instance;

	// methods

	@Override
	public boolean equals(Object object) {
		if (object == this) {
			return true;
		}
		if (object == null || getClass() != object.getClass()) {
			return false;
		}
		ProblemDetailsVO other = (ProblemDetailsVO) object;
		return java.util.Objects.equals(type, other.type)
				&& java.util.Objects.equals(title, other.title)
				&& java.util.Objects.equals(status, other.status)
				&& java.util.Objects.equals(detail, other.detail)
				&& java.util.Objects.equals(instance, other.instance);
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(type, title, status, detail, instance);
	}

	@Override
	public String toString() {
		return new StringBuilder()
				.append("ProblemDetailsVO[")
				.append("type=").append(type).append(",")
				.append("title=").append(title).append(",")
				.append("status=").append(status).append(",")
				.append("detail=").append(detail).append(",")
				.append("instance=").append(instance)
				.append("]")
				.toString();
	}

	// fluent

	public ProblemDetailsVO type(java.net.URI newType) {
		this.type = newType;
		return this;
	}

	public ProblemDetailsVO title(String newTitle) {
		this.title = newTitle;
		return this;
	}

	public ProblemDetailsVO status(Integer newStatus) {
		this.status = newStatus;
		return this;
	}

	public ProblemDetailsVO detail(String newDetail) {
		this.detail = newDetail;
		return this;
	}

	public ProblemDetailsVO instance(java.net.URI newInstance) {
		this.instance = newInstance;
		return this;
	}

	// getter/setter

	public java.net.URI getType() {
		return type;
	}

	public void setType(java.net.URI newType) {
		this.type = newType;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String newTitle) {
		this.title = newTitle;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer newStatus) {
		this.status = newStatus;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String newDetail) {
		this.detail = newDetail;
	}

	public java.net.URI getInstance() {
		return instance;
	}

	public void setInstance(java.net.URI newInstance) {
		this.instance = newInstance;
	}
}
